server:
  port: 8089
spring:
  application:
    name: order-service
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: charo
    password: shop
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: 127.0.0.1
#    username: cloudshopping
#    password: cloudshopping
#    virtual-host: /cloudshopping
#    template:
#      retry:
#        enabled: true
#        initial-interval: 10000ms
#        max-interval: 30000ms
#        multiplier: 2
#      exchange: ly.item.exchange
#    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#cloudshopping:
##  jwt:
##    pubKeyPath: /root/cloud_shopping_project/rsa.pub # 公钥地址
##    #    pubKeyPath: F:/IdeaProjects/HwjProjects/auth/rsa/rsa.pub # 公钥地址
##    cookieName: LY_TOKEN
#  worker:
#    workerId: 1
#    dataCentered: 1
#  pay:
#    appId: wx8397f8696b538317
#    mchId: 1473426802
#    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
#    connectTimeoutMs: 5000
#    readTimeoutMs: 10000
#feign:
#  hystrix:
#    enabled: false
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
mybatis:
#  type-aliases-package: com.could.shopping.order
#  mapper-locations: mapper/OrderMapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:/com/cloud/shopping/mapper/*.xml
#  mapper-locations: classpath:/mapper/*.xml
#  mapper-locations: classpath*:/mapper/*.xml
#mapper:
#  not-empty: false
#  identity: mysql

ribbon.eureka.enable: true