server:
#  port: 8080
  port: 8095
spring:
  application:
    name: user-service
#  rabbitmq:
#    host: 192.168.112.101
#    username: cloudshopping
#    password: cloudshopping
#    virtual-host: /cloudshopping
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&amp;characterEncoding=UTF-8
    username: charo
    password: shop
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
#  type-aliases-package: com.cloudshopping.user.entity
  mapper-locations: classpath:/com/cloud/shopping/mapper/*.xml
#  mapper-locations: classpath:/mapper/*.xml

ribbon.eureka.enable: true